# MODE: DEV
# PACKAGE: PROD
# ---------------------------------------------------------------
# 1. Configuration and registries
# ---------------------------------------------------------------
# SKILL_NAMES/SKILL_DESCRIPTIONS and TARGET_NAMES/TARGET_PATHS/TARGET_KINDS are
# index-parallel: usage(), the shop menu, the numeric menu map, and
# agent_kind_for_root() all derive from them, so a new skill or agent is one
# edit here. TARGET_* index order is load-bearing: agent_target_available()
# switches on the index, and index 5 (Cline) owns six alternative detection
# globs. Never reorder or insert; append only.

REPO_URL="${AI_SKILLS_REPO_URL:-https://github.com/tschallacka/ai-skills}"
# The repository's default branch is master; a "main" default 404s on both the
# raw install.sh URL and the archive tarball, which breaks the curl|bash form.
REPO_REF="${AI_SKILLS_REF:-master}"
SOURCE_ROOT=""
TEMP_ROOT=""
SOURCE_VERSION=""
YES=0
SKILL_SELECTION=""
TARGET_SELECTION=""
CLI_MODE=""
CLI_SKILL=""
CLI_FORMAT=""
CLI_RELATIVE=""
CLI_APPROVAL=""

# Filled by verify_runtime_tools() (section 4) and read by main and the summary:
# the installable subset of the selection, and the space-joined names that a
# missing hard requirement removed from it.
RUNTIME_READY_SKILLS=()
RUNTIME_BLOCKED_SKILLS=""
# One formatted line per destination, appended by install_skill() (section 11)
# and printed as the end-of-run summary (section 11b).
SUMMARY_LINES=()
SUMMARY_PRINTED=0

PACKAGE_SELECTION="${PACKAGE_SELECTION:-prod}"
# How a skill is driven, for the skills that offer a choice (integration.tsv).
#
# INTEGRATION_DEFAULT applies to every such skill; INTEGRATION_SELECTION holds
# newline-delimited `skill=mode` records that override it per skill. Both are
# honoured from the environment so a CI job can set them without composing
# arguments.
#
# EDITOR_INTEGRATION is the older name for the ai-text-editor choice alone, kept
# because it is documented and scripted against. It seeds the per-skill record
# rather than living on as a second mechanism, so there is exactly one place the
# decision is read from.
INTEGRATION_DEFAULT="${INTEGRATION_DEFAULT:-skill}"
INTEGRATION_SELECTION="${INTEGRATION_SELECTION:-}"
if [ -n "${EDITOR_INTEGRATION:-}" ]; then
    INTEGRATION_SELECTION="ai-text-editor=$EDITOR_INTEGRATION
$INTEGRATION_SELECTION"
fi

# The two tables below are GENERATED by installer/build.sh from each skill's
# integration.tsv. Edit those files, not this block, and re-run
# installer/build.sh.
#
# They live here, in the configuration section, rather than beside the filter
# that reads them: section 2 parses arguments at TOP LEVEL, so a validator that
# rejects an unoffered mode has to be able to call integration_modes() before
# section 5 has been reached.
# BEGIN GENERATED INTEGRATION BLOCK
# END GENERATED INTEGRATION BLOCK

# Record one --integration argument: `mode`, or `skill=mode`.
#
# Validated here rather than at install time, because the whole point of the
# flag is an unattended run: an agent that mistypes a mode must be told at the
# door, with the modes that do exist, instead of getting a silent default
# install that looks like success. A skill offering no choice is refused for the
# same reason -- naming one is a mistake about the tool, not a preference.
# Every mode any skill declares, space-delimited on both sides.
#
# `skill` is always in the union even when nothing declares it, because it is
# the mode every undeclared skill is already installed in. Deduped, because a
# refusal prints this list and "skill skill mcp" reads like a bug in the
# installer rather than an answer to the question asked.
integration_declared_modes() {
    local known mode_name offered=' skill '
    for known in ${SKILL_NAMES[@]+"${SKILL_NAMES[@]}"}; do
        while IFS= read -r mode_name; do
            [ -n "$mode_name" ] || continue
            case "$offered" in
                *" $mode_name "*) continue ;;
            esac
            offered="$offered$mode_name "
        done <<INTEGRATION_MODES_EOF
$(integration_modes "$known")
INTEGRATION_MODES_EOF
    done
    printf '%s' "$offered"
}

# Record `<skill>=<mode>`, refusing a mode that skill does not offer.
#
# Both delimiters in the match, or the FIRST mode never matches: the joined list
# ends with a space but does not begin with one.
record_skill_integration() {
    local skill="$1" mode="$2" offered
    offered="$(integration_modes "$skill" | tr '\n' ' ')"
    [ -n "$offered" ] \
        || die_usage "$skill offers no integration modes to choose between"
    case " $offered" in
        *" $mode "*) : ;;
        *) die_usage "$skill has no $mode integration; it offers: $offered" ;;
    esac
    INTEGRATION_SELECTION="$skill=$mode
$INTEGRATION_SELECTION"
}

record_integration() {
    local argument="$1" skill mode offered
    case "$argument" in
        *=*) skill="${argument%%=*}"; mode="${argument#*=}" ;;
        *) skill=''; mode="$argument" ;;
    esac
    [ -n "$mode" ] || die_usage "--integration needs a mode, or skill=mode"
    if [ -n "$skill" ]; then
        record_skill_integration "$skill" "$mode"
        return 0
    fi
    offered="$(integration_declared_modes)"
    case "$offered" in
        *" $mode "*) : ;;
        *) die_usage "no skill offers a $mode integration; declared modes are:$offered" ;;
    esac
    INTEGRATION_DEFAULT="$mode"
}

SKILL_NAMES=(planning project-specificies resource-limited-testing brainstorm post-implementation-review todo bug-report chat git-worktrees git-merge-resolving merge-request-etiquette text-etiquette ai-text-editor interactive-shell)
SKILL_DESCRIPTIONS=(
    'Durable, resumable plans with steps and verification.'
    'Records project conventions, quirks, and deviations.'
    'Caps CPU and memory for demanding tool runs.'
    'Shapes an idea into a recorded, agreed picture before planning.'
    'After-the-fact review and proposed fixes for built code.'
    'A nested queue of work in one JSON file, read with rjq.'
    'Defects with their reproduction, mechanism and verification, in JSON.'
    'IRC-basis agent chat over TLS: a rust server and client, UDP discovery, deltas.'
    'Separate checkouts so parallel work and long verifications cannot collide.'
    'Conflicts resolved by what each side changed, and a merged tree you can trust.'
    'Merge requests in your voice: own branch, one squashed commit, a TLDR, then the fix.'
    'Shorthand and a clipped register for an agent prose: chat, dev talk, and its own thinking. Short, factual, no people-please prose; plain english on request.'
    'Server-owned editor tabs for agents: bounded reads, explicit search modes, revision-aware edits, undo/redo, raw-byte and hex access, SQLite metadata, and Unix-socket or TCP transport.'
    'Drives unknown full-screen terminal programs through a PTY wrapper and a unix-socket input client.'
)

# The detail pane's body: a summary sentence, then what it actually does. Kept
# here rather than read from each skill's SKILL.md because select_skills() runs
# before download_source() -- under `curl … | bash` no skill directory exists
# yet, so anything the picker shows must be baked in at build time.
#
# Index-parallel with SKILL_NAMES, which test-installer-skill-selection.sh
# enforces: git-worktrees was added to SKILL_NAMES without a description, and
# moving the cursor onto it killed the picker with an unbound variable.
SKILL_DETAILS=(
    'Turns an initiative into a directory of files another agent can resume without reconstructing context.
Goals own one outcome each and hold 2-10 work units; a work unit is one file and one symbol, so every change is separately reviewable.
Steps carry instructions, acceptance criteria and the handoff the next unit relies on.
Validation refuses a plan whose units nothing verifies, and a fresh adversarial reviewer must approve it before execution.
Where a plan touches a UI, browser stories with real interaction are mandatory rather than optional.'
    'Records what a project does differently, so the next session does not rediscover it.
Load the matching note when a convention, environment quirk or tooling deviation could change how you implement, debug or test.
Newly confirmed deviations are written back, which is what keeps the note worth reading.
Not for documentation that follows the ecosystem defaults -- only the surprises.'
    'Runs a command under a CPU and memory cap, so a heavy test, build or analyzer cannot take the machine with it.
Wraps the command rather than the tool: no configuration inside the thing being limited.
On Apple Silicon macOS it uses memlimit, the one documented exception to this repository dependency ceiling, because macOS offers no other way to cap memory.
Without memlimit it says so and still limits CPU through nice and cpulimit, rather than pretending the cap is in force.'
    'A short recorded back-and-forth that settles what to build before anything is planned or written.
Use it when a request could branch in materially different directions and the wrong branch is expensive.
The output is an agreed picture, not a plan: it feeds the planning skill rather than replacing it.
Skip it for small or fully specified changes, where the discussion costs more than the work.'
    'Reviews an implementation after the fact, from three angles that disagree on purpose.
The implementer analyses its own work, an independent agent proposes alternatives, and a critical agent attacks both.
It ends in concrete proposed fixes rather than a verdict.
Not a substitute for the pre-implementation adversarial review, which asks a different question: this one sees the code that exists.'
    'A nested queue of work in one JSON file, read and written with rjq.
For work that outlives the conversation and must survive a restart, a handoff or a compaction.
Every task carries its status and its detail, so a cold reader knows what was intended and what is left.
Not for the steps of a task already in progress, and not for defects -- those belong in the bug register.'
    'Defects recorded with the reproduction, the observed output, the mechanism once established, and the verification that closes them.
One defect per entry: if stating it needs the word "and", it is two entries that reference each other.
An entry closes only with a fix and a verification naming the mutation that fails without it, so a closure cannot be a claim.
Written only through its helpers -- an out-of-enum value makes the register unsound and every later write refuses.'
    'An IRC-over-TLS message bus for agents: a rust server that a standard TLS IRC client could join, and a rust client.
The server speaks the RFC 1459 grammar over TLS and mints its self-signed certificate at first run.
The client discovers servers over UDP, pins the certificate (TOFU), and sends / reads a delta since an id / tails.
History is additive: an agent fetches the messages after id N via the FETCH extension, instead of re-reading a whole channel.'
    'Gives a task its own checkout, so several agents can work at once without seeing each other half-finished edits.
Also isolates a long verification from later commits, and keeps a risky change off the main checkout.
Covers the concurrency hazard that silently fails a long-running command when two runs share a tree.
And the part that is usually learned late: the order to merge the branches back in, and which conflict classes to expect.'
    'Decides what a conflicted file should say once both changes exist, rather than reaching for --ours or --theirs.
Reads each side out of history -- what changed, what the commit said, when, and which side is the file lineage that kept evolving.
Names the conflicts that are unions rather than choices, and the ones git reports clean while the meaning is wrong.
Generated output is regenerated, never stitched; an unresolved generated file counts every symbol twice and fakes a ratchet jump.
Every post-merge failure is run against both parents first, so an inherited failure is reported rather than absorbed into the merge.'
    'Writes the merge request description in the voice of the person whose name is on it, opening with a one-paragraph TLDR.
The body names the defect, the cause and the change, and stops there: no headings for their own sake, no restating the diff.
The reasoning is derived from git log for the branch, so a description never explains what a commit message should have said.
Chat transcripts never travel, and a collapsible block is allowed only for evidence the commits genuinely cannot carry.'
    'Tells an agent how to talk everywhere verbosity creeps in: chat with agents, dev talk with the developer, and its own thinking prose.
The register is caveman-tight: facts first, fragments fine, paths and errors exact while the wrapper around them shrinks.
Praise stops at gj, corrections are applied without thanks, and unknown shorthand is asked about, never guessed.
The reader may always ask for plain english; the register bends only where brevity would cost understanding.'
    'Keeps file state on a server so clients can request bounded reads and edits without embedding editor state.
Supports UTF-8, raw-byte and hex startup modes, explicit exact/wildcard/regex/fuzzy search choices, and revision-guarded saves.
Each tab records identity and revision in its own SQLite database; TCP is available where Unix sockets are unavailable.'
    'Lets an agent operate a full-screen terminal program it has never seen: nano, mc, lynx, a pager, a menu.
A rust wrapper allocates a real PTY and publishes each screen change as one JSONL event; a socket client sends keys, combos, pastes, mouse events and resizes.
Observation is the point: compact row views and deltas keep context small, and element discovery reports what is actually on screen rather than assuming a shortcut.
An acknowledgement means the wrapper accepted the input, never that the program acted on it, so every state change is confirmed against the next screen.
POSIX only, and the screen model is honest about its limits: byte-oriented cells, so non-ASCII widths are approximate.'
)
TARGET_NAMES=(
    "Universal Agent Skills"
    "Codex"
    "Claude Code"
    "OpenCode"
    "OpenClaw"
    "Cline"
)
TARGET_PATHS=(
    "$HOME/.agents/skills"
    "$HOME/.codex/skills"
    "$HOME/.claude/skills"
    "$HOME/.config/opencode/skills"
    "$HOME/.openclaw/skills"
    "$HOME/.cline/skills"
)
TARGET_KINDS=(
    universal
    codex
    claude
    opencode
    openclaw
    cline
)
CUSTOM_LOCATIONS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/tsch-ai-skills/custom-locations"

# Detected once by detect_color_mode(); see section 6.
COLOR_MODE=""

# Mascot pixel art: 16 rows of 16 six-hex-digit pixels, one row per line, each
# pixel doubled horizontally by render_art() so the sprite comes out square.
# Rows 8 and 9 are the eyes and are substituted per frame by render_art(). This
# lives here rather than inside show_splash() because render_art() reads it as an
# implicit global, which used to make render_art() unusable before show_splash().
ART=(
    'f2cf38 f2cf38 fdc100 fdc100 fcf246 fcf246 e8b11a e8b11a fcdb28 fcdb28 fcd228 fcd228 fdfd5e fcfd5f fcf347 fcf347'
    'f2cf38 f2cf38 fdc100 fdc100 fcf246 fcf246 e8b11a e8b11a fcdb28 fcdb28 fcd228 fcd228 fbfb5d fdfd5e fcf347 fcf347'
    'e8be38 e8be38 fcd84b fcd84b fdc100 fdc100 fcdb28 fcdb28 fcdb28 fcdb28 e8b11a e8b11a fddc51 fddc51 fdbb37 fdbb37'
    'e8be38 e8be38 fcd84b fcd84b fdc100 fdc100 fcdb28 fcdb28 fcdb28 fcdb28 e8b11a e8b11a fcdc51 fcdc51 fdbb37 fdbb37'
    'c37f18 c37f18 fdc127 fdc127 e6a621 e6a621 fcd22b fcd22b fdc127 fdc127 e6a621 e6a621 e6a621 e6a621 c37f18 c37f18'
    'c37f18 c37f18 fdc127 fdc127 e6a621 e6a621 fcd22b fcd22b fdc127 fdc127 e6a621 e6a621 e6a621 e6a621 c37f18 c37f18'
    'd8a521 d8a521 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 c37f18 c37f18'
    'd8a521 d8a521 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 2d1b00 c37f18 c37f18'
    'c27f18 c27f18 fbfbfb fbfbfb 009c00 009c00 c27417 c27417 dd8100 df8200 009c00 009c00 fbfbfb fbfbfb d68601 d68601'
    'c27f18 c27f18 6c3100 6c3100 c27f18 c27f18 67522d 67522d 67522d 67522d 883300 883300 c27f18 c27f18 6c3100 6c3100'
    '623b00 623b00 321400 321400 3a2910 3a2910 67522d 67522d 67522d 67522d 3a2910 3a2910 6c3100 6c3100 210000 210000'
    '623b00 623b00 321400 321400 3a2910 3a2910 67522d 67522d 67522d 67522d 3a2910 3a2910 6c3100 6c3100 210000 210000'
    '280c02 280c02 300d0a 300d0a 240a00 240a00 67522d 67522d 67522d 67522d 3e0907 3e0907 300d0a 300d0a 210000 210000'
    '280c02 280c02 300d0a 300d0a 240a00 240a00 67522d 67522d 67522d 67522d 3e0907 3e0907 300d0a 300d0a 210000 210000'
    '300d0a 300d0a 280c02 280c02 240a00 240a00 67522d 67522d 67522d 67522d 210000 210000 3e0907 3e0907 240a00 240a00'
    '300d0a 300d0a 280c02 280c02 240a00 240a00 67522d 67522d 67522d 67522d 210000 210000 3e0907 3e0907 240a00 240a00'
)

usage() {
    cat <<'EOF'
Usage: install.sh [options]

Interactive by default. Options are useful for automation:
  --all                    Install or update all skills
  --skill <name>           Install or update a skill; repeatable, and the value
                           may be a comma-separated list
  --package prod|dev       prod (default) installs what an end user needs;
                           dev adds the files only a maintainer does
  --integration <mode>     Choose how a skill is driven, for the skills that
  --integration <skill>=<mode>
                           offer a choice. `skill` (default) installs the
                           client the skill's own instructions drive; `mcp`
                           installs the MCP bridge an agent calls as typed
                           tools instead. Repeatable, and the bare form applies
                           to every skill that offers the mode. An unoffered
                           mode is refused by name rather than silently
                           defaulting, and switching does not stop live servers.
  --editor-integration skill|mcp
                           The older name for --integration ai-text-editor=…,
                           kept for scripts that already pass it.
  --target <path>          Install into one skill root without prompting
  --yes                    Answer yes to every prompt, including the planning
                           permission grants; an edited file is still backed up  
  --help                   Show this help

Interactive prompts accept a for "yes to all" (auto-accepts every
remaining confirmation, e.g. replace/backup prompts and permission grants).

Supported skills:
EOF
    printf '  %s\n' "${SKILL_NAMES[@]}"
}

die() {
    echo "Error: $*" >&2
    exit 1
}

# A usage error, which CODE-CONTRACTS.md §12 gives its own exit code: 64 is "you
# invoked this wrong", distinguishable from 1.
#
# It matters most for the case it was added for. An unattended installer run --
# an agent choosing `--integration mcp` for itself -- has only the exit status
# to go on, and a mistyped mode returning the same 1 as a failed copy or a
# refused overwrite leaves it unable to tell "fix your arguments" from "the
# machine is not in a state where this can work".
die_usage() {
    echo "Error: $*" >&2
    exit 64
}
