# ---------------------------------------------------------------
# 4. Runtime tool verification
# ---------------------------------------------------------------
# Some skills need tools on the target system at runtime (not at install time).
# Requirement strength decides what a missing one costs, and it is per skill so
# one unsatisfiable dependency never stops the others:
#   hard — the skill does not work at all, so it is not installed and the run
#          exits non-zero (a partial install must not read as success in CI)
#   soft — the skill degrades honestly, so it is installed with a warning
#          naming the capability that is lost; the exit status is unaffected
#
# A requirement may be platform- and arch-conditional: resource-limited-testing
# only names memlimit on Darwin:arm64, because memlimit does not support Intel
# Macs and demanding it there would refuse a skill whose degraded path works.
#
# The four tables below are GENERATED by installer/build.sh from each skill's
# requires.tsv and the shared installer/tools.tsv. Edit those files, not this
# block, and re-run installer/build.sh.
# BEGIN GENERATED DEPENDENCY BLOCK
# END GENERATED DEPENDENCY BLOCK

# A skill is installable when every hard requirement is met. A missing soft one
# is deliberately not consulted here — it costs a warning, not the install.
skill_runtime_tools_present() {
    local tool
    while IFS= read -r tool; do
        [ -n "$tool" ] || continue
        [ "$(runtime_requirement_strength "$1" "$tool")" = hard ] || continue
        runtime_tool_verify "$tool" || return 1
    done < <(runtime_requirements "$1")
    return 0
}

# The unmet requirements of one skill at one strength, one tool per line.
runtime_unmet_tools() {
    local skill="$1" strength="$2" tool
    while IFS= read -r tool; do
        [ -n "$tool" ] || continue
        [ "$(runtime_requirement_strength "$skill" "$tool")" = "$strength" ] || continue
        runtime_tool_verify "$tool" || printf '%s\n' "$tool"
    done < <(runtime_requirements "$skill")
}

runtime_report_missing() {
    local skill="$1" tool="$2"
    printf '  - %s (%s requirement of %s)\n' "$tool" \
        "$(runtime_requirement_strength "$skill" "$tool")" "$skill" >&2
    printf '    lost without it: %s\n' "$(runtime_requirement_why "$skill" "$tool")" >&2
    printf '    install it with:\n' >&2
    runtime_tool_install_hint "$tool" >&2
}

# Ready-to-paste lines for the skills that are installable now, so a blocked
# --all is never a dead end. The end-of-run summary carries the full replay.
runtime_report_way_forward() {
    local skill ready=""
    for skill in "$@"; do
        skill_runtime_tools_present "$skill" && ready="$ready $skill"
    done
    [ -n "$ready" ] || return 0
    echo >&2
    echo "The skills that are ready now can be installed one at a time:" >&2
    # Unquoted on purpose: $ready is a space-joined list of skill names.
    for skill in $ready; do
        printf '  install.sh --skill %s\n' "$skill" >&2
    done
}

# Partitions "$@" into RUNTIME_READY_SKILLS and RUNTIME_BLOCKED_SKILLS and
# reports every gap on stderr. Callers install the ready list and exit non-zero
# when the blocked list is not empty.
verify_runtime_tools() {
    local skill tool
    RUNTIME_READY_SKILLS=()
    RUNTIME_BLOCKED_SKILLS=""
    for skill in "$@"; do
        while IFS= read -r tool; do
            [ -n "$tool" ] || continue
            echo >&2
            printf 'Warning: %s installs in a degraded form.\n' "$skill" >&2
            runtime_report_missing "$skill" "$tool"
        done < <(runtime_unmet_tools "$skill" soft)
        if skill_runtime_tools_present "$skill"; then
            RUNTIME_READY_SKILLS+=("$skill")
            continue
        fi
        RUNTIME_BLOCKED_SKILLS="$RUNTIME_BLOCKED_SKILLS $skill"
        echo >&2
        printf 'Not installing %s: a hard requirement is missing.\n' "$skill" >&2
        while IFS= read -r tool; do
            [ -n "$tool" ] || continue
            runtime_report_missing "$skill" "$tool"
        done < <(runtime_unmet_tools "$skill" hard)
    done
    [ -n "$RUNTIME_BLOCKED_SKILLS" ] || return 0
    runtime_report_way_forward "$@"
}

