# MODE: DEV
# PACKAGE: PROD
# ---------------------------------------------------------------
# 4. Runtime tool verification
# ---------------------------------------------------------------
# Some skills need tools on the target system at runtime (not at install time).
# Requirement strength decides what a missing one costs, and it is per skill so
# one unsatisfiable dependency never stops the others:
#   hard — the skill does not work at all, so it is not installed and the run
#          exits non-zero (a partial install must not read as success in CI)
#   soft — the skill degrades honestly, so it is installed with a warning
#          naming the capability that is lost; the exit status is unaffected
#
# A requirement may be platform- and arch-conditional: resource-limited-testing
# only names memlimit on Darwin:arm64, because memlimit does not support Intel
# Macs and demanding it there would refuse a skill whose degraded path works.
#
# A row may also name a GROUP (fifth requires.tsv column): the requirement is
# met when any member resolves, so a python3->node->perl chain warns once when
# none is present instead of once per missing tool. A
# hard group gates exactly like a hard single tool; strength is per group.
#
# The four tables below are GENERATED by installer/build.sh from each skill's
# requires.tsv and the shared installer/tools.tsv. Edit those files, not this
# block, and re-run installer/build.sh.
# BEGIN GENERATED DEPENDENCY BLOCK
# END GENERATED DEPENDENCY BLOCK

# Called by artifact selection when no prebuilt overview matches the host. Keep
# this separate from selection so the installer can state the degraded result
# without leaving a partial renderer behind.
plan_overview_unavailable() {
    local os="$1"
    local arch="$2"
    printf 'Plan overview unavailable on this platform (%s:%s): no prebuilt artifact is available.\n' \
        "$os" "$arch" >&2
    return 1
}

# Return the Rust target triple for the host. Test mode supplies the same two
# inputs production detection reads, so selection tests exercise this function.
normalize_platform() {
    local os arch
    if [ "${PLAN_OVERVIEW_TEST_MODE:-0}" = 1 ]; then
        os="${PLAN_OVERVIEW_TEST_OS:-}"
        arch="${PLAN_OVERVIEW_TEST_ARCH:-}"
    else
        os="$(uname -s)"
        arch="$(uname -m)"
    fi
    case "$os:$arch" in
        Linux:x86_64|Linux:amd64) printf '%s\n' x86_64-unknown-linux-musl ;;
        Linux:aarch64|Linux:arm64) printf '%s\n' aarch64-unknown-linux-musl ;;
        Darwin:x86_64|Darwin:amd64) printf '%s\n' x86_64-apple-darwin ;;
        Darwin:arm64|Darwin:aarch64) printf '%s\n' aarch64-apple-darwin ;;
        Windows_NT:AMD64|Windows_NT:x86_64) printf '%s\n' x86_64-pc-windows-msvc ;;
        *) return 1 ;;
    esac
}

plan_overview_selected_artifact() {
    local target path os arch
    os="${PLAN_OVERVIEW_TEST_OS:-$(uname -s)}"
    arch="${PLAN_OVERVIEW_TEST_ARCH:-$(uname -m)}"
    target="$(normalize_platform)" || {
        plan_overview_unavailable "$os" "$arch"
        return 1
    }
    path="bin/$target/plan-overview"
    [ "$target" = x86_64-pc-windows-msvc ] && path="$path.exe"
    if [ -n "${SOURCE_ROOT:-}" ] && [ ! -f "$SOURCE_ROOT/planning/$path" ]; then
        plan_overview_unavailable "$os" "$arch"
        return 1
    fi
    printf '%s\n' "$path"
}

# The bundled rjq artifact path for this host, or nothing when the host matches
# no row. PATH prepending and the install-time skip both read this, so the case
# table lives here once.
bundled_rjq_artifact() {
    case "$(uname -s):$(uname -m)" in
        Linux:x86_64|Linux:amd64) printf '%s\n' 'bin/x86_64-unknown-linux-musl/rjq' ;;
        Linux:aarch64|Linux:arm64) printf '%s\n' 'bin/aarch64-unknown-linux-musl/rjq' ;;
        Darwin:x86_64) printf '%s\n' 'bin/x86_64-apple-darwin/rjq' ;;
        Darwin:arm64) printf '%s\n' 'bin/aarch64-apple-darwin/rjq' ;;
        MINGW*:x86_64|MSYS*:x86_64|CYGWIN*:x86_64|Windows*:x86_64|MINGW*:amd64|MSYS*:amd64|CYGWIN*:amd64|Windows*:amd64)
            printf '%s\n' 'bin/x86_64-pc-windows-msvc/rjq.exe' ;;
    esac
}

bundled_rjq_missing_notice() {
    printf 'Note: no bundled rjq for this host; the register helpers need rjq.\n' >&2
    printf '  Download the artifact from the project releases page (queued as T70), run ./setup-dev-env.sh,\n' >&2
    printf '  or build src/rjq with ./bootstrap.sh when nix is unavailable.\n' >&2
}

# Make the source bundle available before dependency checks. This keeps installs
# independent of a system jq/rjq package while preserving PATH lookup semantics.
prepend_bundled_rjq() {
    local artifact
    artifact="$(bundled_rjq_artifact)" || return 0
    [ -n "$artifact" ] || return 0
    if [ -x "$SOURCE_ROOT/planning/$artifact" ]; then
        PATH="$SOURCE_ROOT/planning/$(dirname "$artifact"):$PATH"
        export PATH
    else
        bundled_rjq_missing_notice
    fi
}

# A skill is installable when every hard requirement is met. A missing soft one
# is deliberately not consulted here — it costs a warning, not the install.
skill_runtime_tools_present() {
    local tool
    while IFS= read -r tool; do
        [ -n "$tool" ] || continue
        [ "$(runtime_requirement_strength "$1" "$tool")" = hard ] || continue
        runtime_requirement_met "$tool" || return 1
    done < <(runtime_requirements "$1")
    return 0
}

# The unmet requirements of one skill at one strength, one entry per line: a
# tool id, or an @group standing for its any-of members.
runtime_unmet_tools() {
    local skill="$1" strength="$2" tool
    while IFS= read -r tool; do
        [ -n "$tool" ] || continue
        [ "$(runtime_requirement_strength "$skill" "$tool")" = "$strength" ] || continue
        runtime_requirement_met "$tool" || printf '%s\n' "$tool"
    done < <(runtime_requirements "$skill")
}

# How a report names a requirement: an @group reads as its member list, a
# single tool as itself.
runtime_requirement_label() {
    local entry="$1" member label=""
    case $entry in
        @*)
            while IFS= read -r member; do
                [ -n "$member" ] || continue
                label="${label:+$label, }$member"
            done < <(runtime_requirement_members "$entry")
            printf 'any of %s' "$label"
            ;;
        *) printf '%s' "$entry" ;;
    esac
}

# Whether one requirement entry is satisfied. A group needs any one member; the
# first success wins, because the chain falls through in preference order.
runtime_requirement_met() {
    local entry="$1" member
    case $entry in
        @*)
            while IFS= read -r member; do
                [ -n "$member" ] || continue
                if runtime_tool_verify "$member"; then
                    return 0
                fi
            done < <(runtime_requirement_members "$entry")
            return 1
            ;;
        *) runtime_tool_verify "$entry" ;;
    esac
}

# Install guidance for one requirement entry: a missing group recommends its
# first member, which is the head of the chain and so the preferred install.
runtime_requirement_install_hint() {
    local entry="$1" first=""
    case $entry in
        @*)
            first="$(runtime_requirement_members "$entry" | sed -n '1p')"
            runtime_tool_install_hint "$first"
            ;;
        *) runtime_tool_install_hint "$1" ;;
    esac
}

runtime_report_missing() {
    local skill="$1" entry="$2"
    printf '  - %s (%s requirement of %s)\n' \
        "$(runtime_requirement_label "$entry")" \
        "$(runtime_requirement_strength "$skill" "$entry")" "$skill" >&2
    printf '    lost without it: %s\n' "$(runtime_requirement_why "$skill" "$entry")" >&2
    if [ "${entry#@}" != "$entry" ]; then
        printf '    install one of them with:\n' >&2
    else
        printf '    install it with:\n' >&2
    fi
    runtime_requirement_install_hint "$entry" >&2
}

# Ready-to-paste lines for the skills that are installable now, so a blocked
# --all is never a dead end. The end-of-run summary carries the full replay.
runtime_report_way_forward() {
    local skill ready=""
    for skill in "$@"; do
        skill_unsupported_here "$skill" >/dev/null && continue
        skill_runtime_tools_present "$skill" && ready="$ready $skill"
    done
    [ -n "$ready" ] || return 0
    echo >&2
    echo "The skills that are ready now can be installed one at a time:" >&2
    # Unquoted on purpose: $ready is a space-joined list of skill names.
    for skill in $ready; do
        printf '  install.sh --skill %s\n' "$skill" >&2
    done
}

# Partitions "$@" into RUNTIME_READY_SKILLS and RUNTIME_BLOCKED_SKILLS and
# reports every gap on stderr. Callers install the ready list and exit non-zero
# when the blocked list is not empty.
verify_runtime_tools() {
    local skill tool reason
    RUNTIME_READY_SKILLS=()
    RUNTIME_BLOCKED_SKILLS=""
    for skill in "$@"; do
        # A skill this platform cannot run is blocked before its requirements
        # are read: there is no tool to install that would change the answer, so
        # the missing-requirement report would name nothing and the way-forward
        # line would offer a command that cannot work.
        if reason="$(skill_unsupported_here "$skill")"; then
            RUNTIME_BLOCKED_SKILLS="$RUNTIME_BLOCKED_SKILLS $skill"
            echo >&2
            printf 'Not installing %s: %s\n' "$skill" "$reason" >&2
            continue
        fi
        while IFS= read -r tool; do
            [ -n "$tool" ] || continue
            echo >&2
            printf 'Warning: %s installs in a degraded form.\n' "$skill" >&2
            runtime_report_missing "$skill" "$tool"
        done < <(runtime_unmet_tools "$skill" soft)
        if skill_runtime_tools_present "$skill"; then
            RUNTIME_READY_SKILLS+=("$skill")
            continue
        fi
        RUNTIME_BLOCKED_SKILLS="$RUNTIME_BLOCKED_SKILLS $skill"
        echo >&2
        printf 'Not installing %s: a hard requirement is missing.\n' "$skill" >&2
        while IFS= read -r tool; do
            [ -n "$tool" ] || continue
            runtime_report_missing "$skill" "$tool"
        done < <(runtime_unmet_tools "$skill" hard)
    done
    [ -n "$RUNTIME_BLOCKED_SKILLS" ] || return 0
    runtime_report_way_forward "$@"
}
