# MODE: DEV
# PACKAGE: PROD
# ---------------------------------------------------------------
# 4. Runtime tool verification
# ---------------------------------------------------------------
# Some skills need tools on the target system at runtime (not at install time).
# Requirement strength decides what a missing one costs, and it is per skill so
# one unsatisfiable dependency never stops the others:
#   hard — the skill does not work at all, so it is not installed and the run
#          exits non-zero (a partial install must not read as success in CI)
#   soft — the skill degrades honestly, so it is installed with a warning
#          naming the capability that is lost; the exit status is unaffected
#
# A requirement may be platform- and arch-conditional: resource-limited-testing
# only names memlimit on Darwin:arm64, because memlimit does not support Intel
# Macs and demanding it there would refuse a skill whose degraded path works.
#
# A row may also name a GROUP (fifth requires.tsv column): the requirement is
# met when any member resolves, so a chat server's python3->node->perl->socat
# chain warns once when none is present instead of once per missing tool. A
# hard group gates exactly like a hard single tool; strength is per group.
#
# The four tables below are GENERATED by installer/build.sh from each skill's
# requires.tsv and the shared installer/tools.tsv. Edit those files, not this
# block, and re-run installer/build.sh.
# BEGIN GENERATED DEPENDENCY BLOCK
# END GENERATED DEPENDENCY BLOCK

# A skill is installable when every hard requirement is met. A missing soft one
# is deliberately not consulted here — it costs a warning, not the install.
skill_runtime_tools_present() {
    local tool
    while IFS= read -r tool; do
        [ -n "$tool" ] || continue
        [ "$(runtime_requirement_strength "$1" "$tool")" = hard ] || continue
        runtime_requirement_met "$tool" || return 1
    done < <(runtime_requirements "$1")
    return 0
}

# The unmet requirements of one skill at one strength, one entry per line: a
# tool id, or an @group standing for its any-of members.
runtime_unmet_tools() {
    local skill="$1" strength="$2" tool
    while IFS= read -r tool; do
        [ -n "$tool" ] || continue
        [ "$(runtime_requirement_strength "$skill" "$tool")" = "$strength" ] || continue
        runtime_requirement_met "$tool" || printf '%s\n' "$tool"
    done < <(runtime_requirements "$skill")
}

# How a report names a requirement: an @group reads as its member list, a
# single tool as itself.
runtime_requirement_label() {
    local entry="$1" member label=""
    case $entry in
        @*)
            while IFS= read -r member; do
                [ -n "$member" ] || continue
                label="${label:+$label, }$member"
            done < <(runtime_requirement_members "$entry")
            printf 'any of %s' "$label"
            ;;
        *) printf '%s' "$entry" ;;
    esac
}

# Whether one requirement entry is satisfied. A group needs any one member; the
# first success wins, because the chain falls through in preference order.
runtime_requirement_met() {
    local entry="$1" member
    case $entry in
        @*)
            while IFS= read -r member; do
                [ -n "$member" ] || continue
                if runtime_tool_verify "$member"; then
                    return 0
                fi
            done < <(runtime_requirement_members "$entry")
            return 1
            ;;
        *) runtime_tool_verify "$entry" ;;
    esac
}

# Install guidance for one requirement entry: a missing group recommends its
# first member, which is the head of the chain and so the preferred install.
runtime_requirement_install_hint() {
    local entry="$1" first=""
    case $entry in
        @*)
            first="$(runtime_requirement_members "$entry" | sed -n '1p')"
            runtime_tool_install_hint "$first"
            ;;
        *) runtime_tool_install_hint "$1" ;;
    esac
}

runtime_report_missing() {
    local skill="$1" entry="$2"
    printf '  - %s (%s requirement of %s)\n' \
        "$(runtime_requirement_label "$entry")" \
        "$(runtime_requirement_strength "$skill" "$entry")" "$skill" >&2
    printf '    lost without it: %s\n' "$(runtime_requirement_why "$skill" "$entry")" >&2
    if [ "${entry#@}" != "$entry" ]; then
        printf '    install one of them with:\n' >&2
    else
        printf '    install it with:\n' >&2
    fi
    runtime_requirement_install_hint "$entry" >&2
}

# Ready-to-paste lines for the skills that are installable now, so a blocked
# --all is never a dead end. The end-of-run summary carries the full replay.
runtime_report_way_forward() {
    local skill ready=""
    for skill in "$@"; do
        skill_runtime_tools_present "$skill" && ready="$ready $skill"
    done
    [ -n "$ready" ] || return 0
    echo >&2
    echo "The skills that are ready now can be installed one at a time:" >&2
    # Unquoted on purpose: $ready is a space-joined list of skill names.
    for skill in $ready; do
        printf '  install.sh --skill %s\n' "$skill" >&2
    done
}

# Partitions "$@" into RUNTIME_READY_SKILLS and RUNTIME_BLOCKED_SKILLS and
# reports every gap on stderr. Callers install the ready list and exit non-zero
# when the blocked list is not empty.
verify_runtime_tools() {
    local skill tool
    RUNTIME_READY_SKILLS=()
    RUNTIME_BLOCKED_SKILLS=""
    for skill in "$@"; do
        while IFS= read -r tool; do
            [ -n "$tool" ] || continue
            echo >&2
            printf 'Warning: %s installs in a degraded form.\n' "$skill" >&2
            runtime_report_missing "$skill" "$tool"
        done < <(runtime_unmet_tools "$skill" soft)
        if skill_runtime_tools_present "$skill"; then
            RUNTIME_READY_SKILLS+=("$skill")
            continue
        fi
        RUNTIME_BLOCKED_SKILLS="$RUNTIME_BLOCKED_SKILLS $skill"
        echo >&2
        printf 'Not installing %s: a hard requirement is missing.\n' "$skill" >&2
        while IFS= read -r tool; do
            [ -n "$tool" ] || continue
            runtime_report_missing "$skill" "$tool"
        done < <(runtime_unmet_tools "$skill" hard)
    done
    [ -n "$RUNTIME_BLOCKED_SKILLS" ] || return 0
    runtime_report_way_forward "$@"
}

