// MODE: DEV
// PACKAGE: PROD

//! Reproduces emit_header/emit_gotchas/emit_gotcha_sightings/
//! emit_recording_docs/emit_verification_docs byte-for-byte.

use crate::rules::Rules;
use std::fmt::Write as _;

pub fn render(rules: &Rules, sightings: &[(String, String, String)], now: &str) -> String {
    let mut out = String::new();
    emit_header(&mut out, rules, now);
    emit_gotchas(&mut out, rules, sightings);
    emit_recording_docs(&mut out);
    emit_verification_docs(&mut out);
    out
}

fn emit_header(out: &mut String, rules: &Rules, now: &str) {
    out.push_str(
        "<!-- Generated by generate-portability.sh from portability-rules.json. Do not edit by hand. -->\n",
    );
    let _ = writeln!(out, "<!-- generated: {now} -->\n");
    out.push_str("# Portability gotchas\n\n");
    out.push_str(
        "Every portability trap this repository has actually hit, in one place, so\n\
         nobody rediscovers one by tripping over it in an unrelated file.\n\
         `CODE-STYLE.md` \u{a7}1 is the contract; this file is the catalogue.\n\n",
    );
    out.push_str(
        "This file is **generated** and cheap to rebuild \u{2014} run `./generate-portability.sh`\n\
         whenever you doubt it. The stamp at the top is when it was last built. If a\n\
         scanned file has been committed since then, regenerate before trusting the\n\
         \"In the tree\" lists; `--check` says so, and reports content drift separately.\n\
         Several agents editing at once will each invalidate it, which is expected:\n\
         regenerate, do not hand-edit, and never resolve a conflict in it by hand.\n\n",
    );
    out.push_str("## Target\n\n| | |\n|---|---|\n");
    let _ = writeln!(out, "| Shell | {} |", rules.target.shell);
    let _ = writeln!(out, "| Userland | {} |", rules.target.userland);
    let _ = writeln!(out, "| Locale | {} |", rules.target.locale);
    out.push_str("\n**Verified:**\n\n");
    let _ = writeln!(
        out,
        "- bash 3.2 \u{2014} {}",
        rules.target.verified.bash_3_2
    );
    let _ = writeln!(
        out,
        "- BSD userland \u{2014} {}\n",
        rules.target.verified.bsd_userland
    );
}

fn emit_gotcha_sightings(out: &mut String, rule_id: &str, sightings: &[(String, String, String)]) {
    let mut matching: Vec<&(String, String, String)> = sightings
        .iter()
        .filter(|(id, _, _)| id == rule_id)
        .collect();
    if matching.is_empty() {
        return;
    }
    matching.sort();
    matching.dedup();
    out.push_str("- **In the tree:**\n");
    for (_, file, why) in matching {
        if why.is_empty() {
            let _ = writeln!(out, "    - `{file}`");
        } else {
            let _ = writeln!(out, "    - `{file}` \u{2014} {why}");
        }
    }
}

fn emit_gotchas(out: &mut String, rules: &Rules, sightings: &[(String, String, String)]) {
    out.push_str("## The gotchas\n\n");
    for rule in &rules.rules {
        let _ = writeln!(out, "### `{}`\n", rule.construct);
        let _ = writeln!(out, "- **Breaks on:** {}", rule.breaks);
        let _ = writeln!(out, "- **Symptom:** {}", rule.symptom);
        let _ = writeln!(out, "- **Use instead:** {}", rule.replacement);
        if let Some(note) = &rule.note {
            let _ = writeln!(out, "- **Note:** {note}");
        }
        if rule.detect.is_none() {
            out.push_str(
                "- **Detection:** none possible \u{2014} this one is a review item, not a grep.\n",
            );
        }
        emit_gotcha_sightings(out, &rule.id, sightings);
        out.push('\n');
    }
}

fn emit_recording_docs(out: &mut String) {
    out.push_str("## Recording a new gotcha\n\nTwo places, and both are required.\n\n");
    out.push_str(
        "**1. `portability-rules.json`** \u{2014} add a rule with `id`, `construct`,\n\
         `detect` (an ERE, or `null` when no grep can find it), `breaks`, `symptom`,\n\
         `replacement`, and an optional `note`. This is the source of truth; the\n\
         sections above are generated from it.\n\n",
    );
    out.push_str(
        "**2. A marker at the site**, in exactly this format:\n\n\
         ```bash\n\
         # PORTABILITY(<rule-id>): <one line, why this local code is shaped this way>\n\
         ```\n\n\
         Rules for the marker:\n\n",
    );
    out.push_str(
        "- The `<rule-id>` MUST match an `id` in `portability-rules.json`. The\n\
         \x20\x20contract test fails on an unknown id, which is what stops the catalogue and\n\
         \x20\x20the code drifting apart.\n",
    );
    out.push_str(
        "- The trailing text is OPTIONAL and at most three lines total, per\n\
         \x20\x20`CODE-STYLE.md` \u{a7}11. Put only what is *local* to this site there. The\n\
         \x20\x20symptom, the platform and the replacement belong in the registry, not\n\
         \x20\x20repeated at every site.\n",
    );
    out.push_str(
        "- Omit the text entirely when the rule id says everything:\n\
         \x20\x20`# PORTABILITY(empty-array-setu)` is a complete marker.\n",
    );
    out.push_str(
        "- Do NOT write the old untagged `# PORTABILITY:` form. It cannot be\n\
         \x20\x20indexed, and the contract test rejects it.\n\n",
    );
    out.push_str(
        "The marker earns its keep twice: it stops the next reader \"simplifying\" the\n\
         workaround back into the bug, and it is what puts the site into this file.\n\n",
    );
}

fn emit_verification_docs(out: &mut String) {
    out.push_str("## Verifying a change\n\n```bash\n");
    out.push_str("nix develop            # provides bash32 and shellcheck\n");
    out.push_str("bash32-run-tests       # the whole suite on the bash 3.2 floor\n");
    out.push_str("./run-tests.sh         # and on your own bash\n");
    out.push_str("bash planning/tests/test-portability-contract.sh\n```\n\n");
    out.push_str(
        "The contract test greps every tracked script for the detectable constructs\n\
         above and fails on a new one, so a gotcha caught once stays caught. It also\n\
         regenerates this file and fails if it is stale.\n",
    );
}

/// The catalogue with its `<!-- generated: ... -->` line removed, for a
/// determinism/parity comparison that must ignore wall-clock time.
pub fn strip_generated_line(text: &str) -> String {
    text.lines()
        .filter(|line| !line.starts_with("<!-- generated: "))
        .collect::<Vec<_>>()
        .join("\n")
}
