#!/usr/bin/env bash
# MODE: DEV
# generate-portability — write PORTABILITY.md from portability-rules.json.
#
# Usage:
#   generate-portability.sh [--check]
#
# --check writes to a temp file and diffs instead of overwriting, exit 1 when
# PORTABILITY.md is stale. planning/tests/test-portability-contract.sh runs it.
#
# PORTABILITY.md is generated so the gotchas cannot drift from the registry and
# so no agent has to rediscover one by tripping over it in an unrelated file.
# Edit portability-rules.json, or the `# PORTABILITY:` comment at the site.
set -euo pipefail
export LC_ALL=C

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
rules="$repo_root/portability-rules.json"
# Overridable so a test can generate two scans to temp paths and compare them.
# Comparing against the committed file instead only answers "is it fresh",
# which is a different question and goes stale for unrelated reasons.
output="${PORTABILITY_OUTPUT:-$repo_root/PORTABILITY.md}"
check_only=false
[ "${1:-}" = "--check" ] && check_only=true
case "${1:-}" in
    -h|--help) awk 'NR == 1 { next }
                    /^#/ {
                        sub(/^#[[:space:]]?/, "")
                        if ($0 ~ /^----[[:space:]]*(quoted:|end quoted)/) next
                        print; next
                    }
                    { exit }' "$0"; exit 0 ;;
esac

command -v rjq >/dev/null 2>&1 || {
    printf '%s: rjq is required to read %s\n' "${0##*/}" "$rules" >&2
    exit 69
}
[ -f "$rules" ] || { printf '%s: missing %s\n' "${0##*/}" "$rules" >&2; exit 66; }

# Every shell script on disk except the archived benchmark output. Deliberately
# not `git ls-files`: a new script is untracked while it is being written, and a
# catalogue that silently skips it is worse than no catalogue.
#
# .claude is pruned because agent worktrees check the repo out underneath it. A
# copy's scripts are the same scripts, so every finding would be listed once per
# worktree, under a path that exists on one machine -- and the freshness check
# would then read the committed catalogue as stale in every clone but that one.
script_list() {
    ( cd "$repo_root" && find . -name '*.sh' -type f \
        -not -path './benchmark/results/*' -not -path './.git/*' -not -path './.plans/*' \
        -not -path './.claude/*' \
        -not -name 'generate-portability.sh' \
        | sed 's|^\./||' | LC_ALL=C sort )
}

# Marker sightings as `<rule-id>|<file>:<line>|<local reason>`, continuation
# lines folded. Used both to publish the catalogue and to validate the ids.
marker_sightings() {
    local file
    while IFS= read -r file; do
        awk -v f="$file" '
            /# PORTABILITY\(/ {
                text = $0
                rule = text
                sub(/^.*# PORTABILITY\(/, "", rule)
                sub(/\).*$/, "", rule)
                sub(/^.*# PORTABILITY\([^)]*\):?[[:space:]]*/, "", text)
                while ((getline nx) > 0 && nx ~ /^[[:space:]]*#/) {
                    sub(/^[[:space:]]*#[[:space:]]*/, "", nx)
                    if (nx != "") text = text " " nx
                }
                gsub(/[[:space:]]+/, " ", text)
                sub(/^[[:space:]]+/, "", text); sub(/[[:space:]]+$/, "", text)
                printf "%s|%s|%s\n", rule, f, text
            }
        ' "$repo_root/$file"
    done < <(script_list)
}

emit() {
    printf '<!-- Generated by generate-portability.sh from portability-rules.json. Do not edit by hand. -->\n'
    printf '<!-- generated: %s -->\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# Portability gotchas\n\n'
    printf 'Every portability trap this repository has actually hit, in one place, so\n'
    printf 'nobody rediscovers one by tripping over it in an unrelated file.\n'
    printf '`CODE-STYLE.md` §1 is the contract; this file is the catalogue.\n\n'
    printf 'This file is **generated** and cheap to rebuild — run `./generate-portability.sh`\n'
    printf 'whenever you doubt it. The stamp at the top is when it was last built. If a\n'
    printf 'scanned file has been committed since then, regenerate before trusting the\n'
    printf '"In the tree" lists; `--check` says so, and reports content drift separately.\n'
    printf 'Several agents editing at once will each invalidate it, which is expected:\n'
    printf 'regenerate, do not hand-edit, and never resolve a conflict in it by hand.\n\n'

    printf '## Target\n\n'
    printf '| | |\n|---|---|\n'
    printf '| Shell | %s |\n' "$(rjq -r '.target.shell' "$rules")"
    printf '| Userland | %s |\n' "$(rjq -r '.target.userland' "$rules")"
    printf '| Locale | %s |\n' "$(rjq -r '.target.locale' "$rules")"
    printf '\n**Verified:**\n\n'
    printf -- '- bash 3.2 — %s\n' "$(rjq -r '.target.verified["bash-3.2"]' "$rules")"
    printf -- '- BSD userland — %s\n\n' "$(rjq -r '.target.verified["bsd-userland"]' "$rules")"

    printf '## The gotchas\n\n'
    local id construct breaks symptom replacement note all_sightings
    all_sightings="$(marker_sightings)"
    while IFS= read -r id; do
        construct="$(rjq -r --arg i "$id" '.rules[]|select(.id==$i)|.construct' "$rules")"
        breaks="$(rjq -r --arg i "$id" '.rules[]|select(.id==$i)|.breaks' "$rules")"
        symptom="$(rjq -r --arg i "$id" '.rules[]|select(.id==$i)|.symptom' "$rules")"
        replacement="$(rjq -r --arg i "$id" '.rules[]|select(.id==$i)|.replacement' "$rules")"
        note="$(rjq -r --arg i "$id" '.rules[]|select(.id==$i)|.note // ""' "$rules")"
        printf '### `%s`\n\n' "$construct"
        printf -- '- **Breaks on:** %s\n' "$breaks"
        printf -- '- **Symptom:** %s\n' "$symptom"
        printf -- '- **Use instead:** %s\n' "$replacement"
        [ -n "$note" ] && printf -- '- **Note:** %s\n' "$note"
        if [ "$(rjq -r --arg i "$id" '.rules[]|select(.id==$i)|.detect' "$rules")" = null ]; then
            printf -- '- **Detection:** none possible — this one is a review item, not a grep.\n'
        fi
        local sightings
        sightings="$(printf '%s\n' "$all_sightings" | awk -F'|' -v r="$id" '$1==r')"
        if [ -n "$sightings" ]; then
            printf -- '- **In the tree:**\n'
            printf '%s\n' "$sightings" | LC_ALL=C sort -u | while IFS='|' read -r _ where why; do
                if [ -n "$why" ]; then
                    printf -- '    - `%s` — %s\n' "$where" "$why"
                else
                    printf -- '    - `%s`\n' "$where"
                fi
            done
        fi
        printf '\n'
    done < <(rjq -r '.rules[].id' "$rules")

    printf '## Recording a new gotcha\n\n'
    printf 'Two places, and both are required.\n\n'
    printf '**1. `portability-rules.json`** — add a rule with `id`, `construct`,\n'
    printf '`detect` (an ERE, or `null` when no grep can find it), `breaks`, `symptom`,\n'
    printf '`replacement`, and an optional `note`. This is the source of truth; the\n'
    printf 'sections above are generated from it.\n\n'
    printf '**2. A marker at the site**, in exactly this format:\n\n'
    printf '```bash\n'
    printf '# PORTABILITY(<rule-id>): <one line, why this local code is shaped this way>\n'
    printf '```\n\n'
    printf 'Rules for the marker:\n\n'
    printf -- '- The `<rule-id>` MUST match an `id` in `portability-rules.json`. The\n'
    printf '  contract test fails on an unknown id, which is what stops the catalogue and\n'
    printf '  the code drifting apart.\n'
    printf -- '- The trailing text is OPTIONAL and at most three lines total, per\n'
    printf '  `CODE-STYLE.md` §11. Put only what is *local* to this site there. The\n'
    printf '  symptom, the platform and the replacement belong in the registry, not\n'
    printf '  repeated at every site.\n'
    printf -- '- Omit the text entirely when the rule id says everything:\n'
    printf '  `# PORTABILITY(empty-array-setu)` is a complete marker.\n'
    printf -- '- Do NOT write the old untagged `# PORTABILITY:` form. It cannot be\n'
    printf '  indexed, and the contract test rejects it.\n\n'
    printf 'The marker earns its keep twice: it stops the next reader "simplifying" the\n'
    printf 'workaround back into the bug, and it is what puts the site into this file.\n\n'

    printf '## Verifying a change\n\n'
    printf '```bash\n'
    printf 'nix develop            # provides bash32 and shellcheck\n'
    printf 'bash32-run-tests       # the whole suite on the bash 3.2 floor\n'
    printf './run-tests.sh         # and on your own bash\n'
    printf 'bash planning/tests/test-portability-contract.sh\n'
    printf '```\n\n'
    printf 'The contract test greps every tracked script for the detectable constructs\n'
    printf 'above and fails on a new one, so a gotcha caught once stays caught. It also\n'
    printf 'regenerates this file and fails if it is stale.\n'
}

# Warn when a scanned file was committed after the recorded generation time.
# git, not mtime: a fresh clone rewrites every mtime and would look stale.
report_age() {
    local stamp doc_at src_at
    stamp="$(sed -n 's/^<!-- generated: \(.*\) -->$/\1/p' "$output" | head -1)"
    [ -n "$stamp" ] || { printf '%s: no generation stamp; regenerate\n' "${0##*/}" >&2; return 0; }
    command -v git >/dev/null 2>&1 || return 0
    git -C "$repo_root" rev-parse --git-dir >/dev/null 2>&1 || return 0
    # Commit ordering in epoch seconds, not the stamp against a commit time: the
    # stamp is written before the commit that carries it, so any commit touching
    # a scanned file would otherwise always look newer. Equal means the same
    # commit, which is fresh.
    doc_at="$(git -C "$repo_root" log -1 --format=%ct -- PORTABILITY.md 2>/dev/null || true)"
    src_at="$(git -C "$repo_root" log -1 --format=%ct -- '*.sh' portability-rules.json 2>/dev/null || true)"
    [ -n "$doc_at" ] && [ -n "$src_at" ] || return 0
    if [ "$src_at" -gt "$doc_at" ]; then
        printf '%s: a scanned file was committed after PORTABILITY.md (stamp %s); regenerate\n' \
            "${0##*/}" "$stamp" >&2
    fi
}

if [ "$check_only" = true ]; then
    temporary="$(mktemp "${TMPDIR:-/tmp}/portability.XXXXXX")"
    trap 'rm -f "$temporary"' EXIT
    emit > "$temporary"
    # Compare content, not the stamp: it changes every run by design.
    if ! diff -u <(grep -v '^<!-- generated: ' "$output") \
                 <(grep -v '^<!-- generated: ' "$temporary"); then
        printf '%s: PORTABILITY.md is stale; run %s\n' "${0##*/}" "${0##*/}" >&2
        exit 1
    fi
    report_age
    printf '%s\n' 'PORTABILITY.md is up to date'
    exit 0
fi

temporary="$(mktemp "$(dirname "$output")/.PORTABILITY.md.XXXXXX")"
trap 'rm -f "$temporary"' EXIT
emit > "$temporary"
mv -f "$temporary" "$output"
trap - EXIT
printf 'Wrote %s\n' "$output"
