// MODE: DEV
// PACKAGE: PROD
use std::env;
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

pub fn project_root_for(input: Option<&str>) -> Result<PathBuf, String> {
    let directory = input.unwrap_or(".");
    let path = Path::new(directory);
    if !path.is_dir() {
        return Err(format!("directory does not exist: {directory}"));
    }
    if let Some(root) = git_value(path, &["rev-parse", "--show-toplevel"]) {
        if !root.is_empty() {
            return canonical_directory(Path::new(&root));
        }
    }
    canonical_directory(path)
}

pub fn home_plans() -> Result<PathBuf, String> {
    let base = env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| {
            env::var_os("HOME")
                .or_else(|| env::var_os("USERPROFILE"))
                .map(|home| PathBuf::from(home).join(".config"))
        })
        .or_else(|| {
            let drive = env::var_os("HOMEDRIVE")?;
            let path = env::var_os("HOMEPATH")?;
            Some(PathBuf::from(drive).join(path).join(".config"))
        })
        .ok_or_else(|| "unable to resolve home directory; set PLANS_ROOT".to_string())?;
    Ok(base.join("tsch-ai-skills").join("plans"))
}

pub fn global_scoped_root(project: &Path) -> Result<PathBuf, String> {
    let plans = home_plans()?;
    let base = project
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default();
    let (owner, repo) = git_remote_namespace(project).unwrap_or_default();
    if !owner.is_empty() && !repo.is_empty() {
        let candidate = plans.join(&owner).join(&repo);
        if candidate.is_dir() {
            return Ok(candidate);
        }
    }
    let user = env::var("USER")
        .or_else(|_| env::var("USERNAME"))
        .unwrap_or_else(|_| "unknown".into());
    Ok(plans.join(user).join(base))
}

pub fn canonical_directory(path: &Path) -> Result<PathBuf, String> {
    fs::canonicalize(path).map_err(|_| format!("directory does not exist: {}", path.display()))
}

pub fn require_safe_value(label: &str, value: &str) -> Result<(), String> {
    if value.is_empty() {
        return Err(format!("{label} must not be empty"));
    }
    if value.contains('|') {
        return Err(format!(
            "{label} must not contain a Markdown table separator (|)"
        ));
    }
    if value.contains('\n') || value.contains('\r') {
        return Err(format!("{label} must be one line"));
    }
    Ok(())
}

pub fn atomic_write(path: &Path, content: &[u8]) -> Result<(), String> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    if !parent.is_dir() {
        return Err(format!("Target directory not found: {}", parent.display()));
    }
    let name = path
        .file_name()
        .and_then(|value| value.to_str())
        .unwrap_or("file");
    let temporary = parent.join(format!(".{name}.{}", std::process::id()));
    let mut file = OpenOptions::new()
        .create_new(true)
        .write(true)
        .open(&temporary)
        .map_err(|_| format!("Cannot create a temp file in: {}", parent.display()))?;
    if let Ok(metadata) = fs::metadata(path) {
        file.set_permissions(metadata.permissions())
            .map_err(|error| error.to_string())?;
    }
    file.write_all(content).map_err(|error| error.to_string())?;
    drop(file);
    fs::rename(&temporary, path).map_err(|error| {
        let _ = fs::remove_file(&temporary);
        error.to_string()
    })
}

pub fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".into();
    }
    if value
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || b"_./-:#".contains(&byte))
    {
        return value.into();
    }
    let mut quoted = String::new();
    for byte in value.bytes() {
        if byte.is_ascii_alphanumeric() || b"_./-:#".contains(&byte) {
            quoted.push(byte as char);
        } else {
            quoted.push('\\');
            quoted.push(byte as char);
        }
    }
    quoted
}

pub fn write_env_manifest(path: &Path, values: &[(&str, String)]) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| format!("manifest has no parent: {}", path.display()))?;
    fs::create_dir_all(parent).map_err(|error| error.to_string())?;
    let temporary = parent.join(format!(".env.tmp.{}", std::process::id()));
    let mut content = String::from("# Generated by plan-env.sh; do not edit.\n");
    for (key, value) in values {
        content.push_str(key);
        content.push('=');
        content.push_str(&shell_quote(value));
        content.push('\n');
    }
    let result = (|| {
        let mut file = OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&temporary)
            .map_err(|error| error.to_string())?;
        file.write_all(content.as_bytes())
            .map_err(|error| error.to_string())?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            file.set_permissions(fs::Permissions::from_mode(0o600))
                .map_err(|error| error.to_string())?;
        }
        drop(file);
        fs::rename(&temporary, path).map_err(|error| error.to_string())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result
}

pub fn git_value(directory: &Path, args: &[&str]) -> Option<String> {
    let output = Command::new("git")
        .arg("-C")
        .arg(directory)
        .args(args)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

pub fn git_remote_namespace(project: &Path) -> Option<(String, String)> {
    let remote = git_value(project, &["remote", "get-url", "origin"])?;
    parse_git_remote_namespace(&remote)
}

pub fn snapshot_repo(plan: &Path) -> Option<PathBuf> {
    let manifest = plan.join(".env");
    let manifest = fs::read_to_string(manifest).ok()?;
    let line = manifest
        .lines()
        .find(|line| line.starts_with("PLAN_SNAPSHOT_REPO="))?;
    let value = line.strip_prefix("PLAN_SNAPSHOT_REPO=")?;
    if value.is_empty() || value.contains(['$', '`', ';', '|', '&', '<', '>']) {
        return None;
    }
    let value = if value.starts_with('\'') && value.ends_with('\'') {
        value[1..value.len() - 1].replace("'\\''", "'")
    } else {
        value.to_string()
    };
    (!value.is_empty()).then(|| PathBuf::from(value))
}

pub fn git_snapshot(plan: &Path) {
    let Some(plan) = plan.canonicalize().ok() else {
        return;
    };
    let Some(repo) = snapshot_repo(&plan) else {
        return;
    };
    if !repo.join(".git").is_dir() {
        return;
    }
    let command = env::args()
        .next()
        .and_then(|value| {
            Path::new(&value)
                .file_name()
                .map(|name| name.to_string_lossy().into_owned())
        })
        .unwrap_or_else(|| "command".into());
    let command = if command.ends_with(".sh") {
        command
    } else {
        format!("{command}.sh")
    };
    let _ = Command::new("git")
        .args(["-C"])
        .arg(&repo)
        .args(["add", "-A", "--"])
        .arg(&plan)
        .output();
    let _ = Command::new("git")
        .args(["-C"])
        .arg(&repo)
        .args([
            "-c",
            "user.name=plan-skill",
            "-c",
            "user.email=plan-skill@localhost",
            "commit",
            "-q",
            "-m",
        ])
        .arg(format!("snapshot before {command}"))
        .output();
}

pub fn parse_git_remote_namespace(remote: &str) -> Option<(String, String)> {
    let path = remote
        .strip_prefix("ssh://")
        .and_then(|value| value.split_once('/').map(|(_, path)| path))
        .or_else(|| {
            remote
                .split_once("git@")
                .and_then(|(_, value)| value.split_once(':').map(|(_, path)| path))
        })
        .or_else(|| {
            remote
                .split_once("://")
                .and_then(|(_, value)| value.split_once('/').map(|(_, path)| path))
        })
        .unwrap_or(remote);
    let mut repo = path.trim_end_matches('/').to_string();
    if repo.ends_with(".git") {
        repo.truncate(repo.len() - 4);
    }
    let (owner, name) = repo.rsplit_once('/')?;
    if name.is_empty() || owner.is_empty() {
        return None;
    }
    Some((owner.to_string(), name.to_string()))
}

#[cfg(test)]
mod tests {
    use super::{
        atomic_write, git_remote_namespace, parse_git_remote_namespace, require_safe_value,
    };
    use std::fs;
    use std::path::Path;

    #[test]
    fn no_remote_is_not_a_namespace() {
        assert!(git_remote_namespace(Path::new("/tmp")).is_none());
    }

    #[test]
    fn remote_keeps_nested_namespace() {
        assert_eq!(
            parse_git_remote_namespace("git@git.example:group/subgroup/project.git"),
            Some(("group/subgroup".into(), "project".into()))
        );
        assert_eq!(
            parse_git_remote_namespace("https://git.example/group/subgroup/project"),
            Some(("group/subgroup".into(), "project".into()))
        );
    }

    #[test]
    fn safe_values_reject_table_breakout_and_newlines() {
        assert!(require_safe_value("label", "plain").is_ok());
        assert!(require_safe_value("label", "bad|cell").is_err());
        assert!(require_safe_value("label", "bad\nvalue").is_err());
    }

    #[test]
    fn atomic_write_replaces_content() {
        let path = std::env::temp_dir().join(format!("planning-core-{}", std::process::id()));
        fs::write(&path, "old").unwrap();
        atomic_write(&path, b"new").unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), "new");
        fs::remove_file(path).unwrap();
    }
}
