// MODE: DEV
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn scratch(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("plan-env-flow-{tag}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

// `write-plan` rewrites the global manifest too. The binary is exec'd from a
// bin/<triple> directory, not from <skill>/scripts, so it must not derive the
// skill directory from its own location: a global manifest that already names
// the skill keeps naming it.
#[test]
fn write_plan_keeps_the_skill_root_the_global_manifest_already_records() {
    let root = scratch("skill-root");
    let plans = root.join("plans");
    let plan = plans.join("demo");
    // plan-env resolves the recorded path, so it has to exist.
    let skill = fs::canonicalize({
        let dir = root.join("skills/planning");
        fs::create_dir_all(&dir).unwrap();
        dir
    })
    .unwrap();
    fs::create_dir_all(&plan).unwrap();
    fs::write(
        plans.join(".env"),
        format!(
            "# Generated by plan-env.sh; do not edit.\nPLAN_ENV_SCHEMA_VERSION=2\nPLANS_ROOT=/old\nPLANNING_SKILL_ROOT={0}\nPLANNING_SCRIPTS_ROOT={0}/scripts\nPLANNING_TESTS_ROOT={0}/tests\n",
            skill.display()
        ),
    )
    .unwrap();

    let output = Command::new(env!("CARGO_BIN_EXE_plan-env"))
        .args(["write-plan"])
        .arg(&plan)
        .arg(&plans)
        .env("PLANS_ROOT", &plans)
        .output()
        .expect("run plan-env write-plan");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let global = fs::read_to_string(plans.join(".env")).unwrap();
    assert!(
        global.contains(&format!("PLANNING_SKILL_ROOT={}\n", skill.display())),
        "{global}"
    );
    assert!(
        global.contains(&format!(
            "PLANNING_SCRIPTS_ROOT={}/scripts\n",
            skill.display()
        )),
        "{global}"
    );

    let _ = fs::remove_dir_all(&root);
}

// A manifest that is well-formed but names another plan is refused: `check`
// has to compare the recorded fields with where the manifest actually sits,
// not only look at its shape.
#[test]
fn check_refuses_a_manifest_copied_in_from_another_plan_and_a_stale_schema() {
    let root = scratch("foreign");
    let plans = root.join("plans");
    let plan = plans.join("demo");
    let other = plans.join("other");
    let skill = root.join("skills/planning");
    fs::create_dir_all(&skill).unwrap();
    fs::create_dir_all(&plan).unwrap();
    fs::create_dir_all(&other).unwrap();
    let skill = fs::canonicalize(&skill).unwrap();
    fs::write(
        plans.join(".env"),
        format!(
            "PLAN_ENV_SCHEMA_VERSION=2\nPLANS_ROOT={0}\nPLANNING_SKILL_ROOT={1}\nPLANNING_SCRIPTS_ROOT={1}/scripts\nPLANNING_TESTS_ROOT={1}/tests\n",
            fs::canonicalize(&plans).unwrap().display(),
            skill.display()
        ),
    )
    .unwrap();

    let run = |args: &[&std::path::Path]| {
        Command::new(env!("CARGO_BIN_EXE_plan-env"))
            .arg(args[0])
            .args(&args[1..])
            .env("PLANS_ROOT", &plans)
            .output()
            .expect("run plan-env")
    };
    let write = run(&["write-plan".as_ref(), &plan, &plans]);
    assert!(
        write.status.success(),
        "{}",
        String::from_utf8_lossy(&write.stderr)
    );
    let valid = run(&["check".as_ref(), &plan, &plans]);
    assert!(
        valid.status.success(),
        "{}",
        String::from_utf8_lossy(&valid.stderr)
    );

    fs::copy(plan.join(".env"), other.join(".env")).unwrap();
    let foreign = run(&["check".as_ref(), &other, &plans]);
    assert_eq!(foreign.status.code(), Some(65));
    assert!(
        String::from_utf8_lossy(&foreign.stderr).contains("plan manifest root mismatch"),
        "{}",
        String::from_utf8_lossy(&foreign.stderr)
    );

    let text = fs::read_to_string(plan.join(".env")).unwrap();
    fs::write(
        plan.join(".env"),
        text.replace("PLAN_ENV_SCHEMA_VERSION=2", "PLAN_ENV_SCHEMA_VERSION=1"),
    )
    .unwrap();
    let stale = run(&["check".as_ref(), &plan, &plans]);
    assert_eq!(stale.status.code(), Some(65));

    let _ = fs::remove_dir_all(&root);
}

// The snapshot pin is written once and survives later `write-plan` calls that
// name no repository, and a repository that is neither the plans root nor the
// plan is refused (64) rather than pinned.
#[test]
fn the_snapshot_pin_survives_a_rewrite_and_a_foreign_repository_is_refused() {
    let root = scratch("pin");
    let plans = root.join("plans");
    let plan = plans.join("demo");
    let elsewhere = root.join("elsewhere");
    let skill = root.join("skills/planning");
    for dir in [&plan, &elsewhere, &skill] {
        fs::create_dir_all(dir).unwrap();
    }
    let plans = fs::canonicalize(&plans).unwrap();
    let plan = fs::canonicalize(&plan).unwrap();
    let skill = fs::canonicalize(&skill).unwrap();
    fs::write(
        plans.join(".env"),
        format!(
            "PLAN_ENV_SCHEMA_VERSION=2\nPLANS_ROOT={0}\nPLANNING_SKILL_ROOT={1}\nPLANNING_SCRIPTS_ROOT={1}/scripts\nPLANNING_TESTS_ROOT={1}/tests\n",
            plans.display(),
            skill.display()
        ),
    )
    .unwrap();
    let run = |args: &[&std::path::Path]| {
        Command::new(env!("CARGO_BIN_EXE_plan-env"))
            .arg(args[0])
            .args(&args[1..])
            .env("PLANS_ROOT", &plans)
            .output()
            .expect("run plan-env")
    };
    let pin_line = format!("PLAN_SNAPSHOT_REPO={}\n", plans.display());

    let pinned = run(&["write-plan".as_ref(), &plan, &plans, &plans]);
    assert!(
        pinned.status.success(),
        "{}",
        String::from_utf8_lossy(&pinned.stderr)
    );
    assert!(fs::read_to_string(plan.join(".env"))
        .unwrap()
        .contains(&pin_line));

    let rewritten = run(&["write-plan".as_ref(), &plan, &plans]);
    assert!(rewritten.status.success());
    assert!(
        fs::read_to_string(plan.join(".env"))
            .unwrap()
            .contains(&pin_line),
        "a later write-plan dropped the pin"
    );

    let foreign = run(&["write-plan".as_ref(), &plan, &plans, &elsewhere]);
    assert_eq!(foreign.status.code(), Some(64));

    let _ = fs::remove_dir_all(&root);
}
