// MODE: DEV
// PACKAGE: PROD
use planning_core::canonical_directory;
use std::env;
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

fn die(message: impl AsRef<str>, code: i32) -> ! {
    eprintln!("plan-env: {}", message.as_ref());
    std::process::exit(code)
}

fn usage(code: i32) -> ! {
    let name = env::args().next().unwrap_or_else(|| "plan-env".into());
    let name = Path::new(&name)
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("plan-env");
    println!("Usage: {name} write-global <plans-root> <planning-root>");
    println!("       {name} write-plan <plan-root> [plans-root] [snapshot-repo]");
    println!("       {name} check <plan-root> [plans-root]");
    println!("       {name} path global|plan <plan-root> [plans-root]");
    println!("       {name} print <plan-root> [plans-root]");
    println!("       {name} --help");
    std::process::exit(code)
}

fn plans_root(explicit: Option<&str>) -> PathBuf {
    if let Some(value) = explicit.filter(|v| !v.is_empty()) {
        return PathBuf::from(value);
    }
    if let Some(value) = env::var_os("PLANS_ROOT") {
        return PathBuf::from(value);
    }
    if let Some(value) = env::var_os("XDG_CONFIG_HOME") {
        return PathBuf::from(value).join("tsch-ai-skills/plans");
    }
    if let Some(value) = env::var_os("HOME").or_else(|| env::var_os("USERPROFILE")) {
        return PathBuf::from(value).join(".config/tsch-ai-skills/plans");
    }
    if let (Some(drive), Some(path)) = (env::var_os("HOMEDRIVE"), env::var_os("HOMEPATH")) {
        return PathBuf::from(drive)
            .join(path)
            .join(".config/tsch-ai-skills/plans");
    }
    die("unable to resolve home directory; set PLANS_ROOT", 66)
}

fn absolute(path: &str) -> PathBuf {
    if !Path::new(path).is_dir() {
        die(format!("directory does not exist: {path}"), 66)
    }
    canonical_directory(Path::new(path)).unwrap_or_else(|message| die(message, 66))
}

fn global_path(root: &Path) -> PathBuf {
    root.join(".env")
}
fn plan_path(root: &Path) -> PathBuf {
    root.join(".env")
}

fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        "''".into()
    } else if value
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || b"_./-".contains(&b))
    {
        value.into()
    } else {
        format!("'{}'", value.replace('\'', "'\\''"))
    }
}

fn write_manifest(path: &Path, values: &[(&str, String)]) {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent).unwrap_or_else(|_| {
        die(
            format!("cannot create manifest directory: {}", parent.display()),
            66,
        )
    });
    let temporary = parent.join(format!(".env.tmp.{}", std::process::id()));
    let mut file = OpenOptions::new()
        .create_new(true)
        .write(true)
        .open(&temporary)
        .unwrap_or_else(|_| {
            die(
                format!(
                    "cannot create manifest temporary file: {}",
                    parent.display()
                ),
                66,
            )
        });
    file.write_all(b"# Generated by plan-env.sh; do not edit.\n")
        .unwrap();
    for (key, value) in values {
        writeln!(file, "{key}={}", shell_quote(value)).unwrap();
    }
    set_mode(&temporary, 0o600);
    drop(file);
    if let Err(error) = fs::rename(&temporary, path) {
        let _ = fs::remove_file(&temporary);
        die(error.to_string(), 66)
    }
}

#[cfg(unix)]
fn set_mode(path: &Path, mode: u32) {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(path, fs::Permissions::from_mode(mode)).unwrap();
}
#[cfg(not(unix))]
fn set_mode(_path: &Path, _mode: u32) {}

fn value(key: &str, value: impl Into<String>) -> (&str, String) {
    (key, value.into())
}

fn read_pinned(path: &Path) -> String {
    let text = fs::read_to_string(path).unwrap_or_default();
    text.lines()
        .find_map(|line| line.strip_prefix("PLAN_SNAPSHOT_REPO="))
        .map(unquote)
        .unwrap_or_default()
}

fn unquote(value: &str) -> String {
    if value.starts_with('\'') && value.ends_with('\'') && value.len() >= 2 {
        value[1..value.len() - 1].replace("'\\''", "'")
    } else {
        value.to_string()
    }
}

fn write_global(root: &Path, skill: &Path) {
    let root = absolute(root.to_str().unwrap());
    let skill = absolute(skill.to_str().unwrap());
    write_manifest(
        &global_path(&root),
        &[
            value("PLAN_ENV_SCHEMA_VERSION", "2"),
            value("PLANS_ROOT", root.display().to_string()),
            value("PLANNING_SKILL_ROOT", skill.display().to_string()),
            value(
                "PLANNING_SCRIPTS_ROOT",
                skill.join("scripts").display().to_string(),
            ),
            value(
                "PLANNING_TESTS_ROOT",
                skill.join("tests").display().to_string(),
            ),
        ],
    );
}

fn write_plan(plan: &Path, root_arg: Option<&str>, snapshot_arg: Option<&str>) {
    let plan = absolute(plan.to_str().unwrap());
    let root = absolute(&plans_root(root_arg).display().to_string());
    let skill = env::args()
        .next()
        .and_then(|p| PathBuf::from(p).parent().map(Path::to_path_buf))
        .and_then(|p| p.parent().map(Path::to_path_buf))
        .unwrap_or_default();
    let manifest = plan_path(&plan);
    let snapshot = snapshot_arg
        .filter(|v| !v.is_empty())
        .map(str::to_string)
        .unwrap_or_else(|| read_pinned(&manifest));
    let snapshot = if snapshot.is_empty() {
        snapshot
    } else {
        let path = absolute(&snapshot);
        if path != root && path != plan {
            die(
                format!(
                    "snapshot repo must be the plans root or the plan root: {}",
                    path.display()
                ),
                64,
            )
        }
        path.display().to_string()
    };
    write_global(&root, &skill);
    let global = global_path(&root);
    write_manifest(
        &manifest,
        &[
            value("PLAN_ENV_SCHEMA_VERSION", "2"),
            value("PLAN_SNAPSHOT_REPO", snapshot),
            value("PLANS_ROOT", root.display().to_string()),
            value("PLAN_ROOT", plan.display().to_string()),
            value("PLAN_NAME", plan.file_name().unwrap().to_string_lossy()),
            value("GLOBAL_PLANS_ENV_FILE", global.display().to_string()),
            value("PLAN_ENV_FILE", manifest.display().to_string()),
            value(
                "PLAN_DESCRIPTION_FILE",
                plan.join("plan-description.md").display().to_string(),
            ),
            value(
                "PLAN_PROGRESS_FILE",
                plan.join("progress.md").display().to_string(),
            ),
            value(
                "PLAN_WORK_UNIT_INVENTORY",
                plan.join("work-unit-inventory.md").display().to_string(),
            ),
            value(
                "PLAN_VALIDATION_FILE",
                plan.join("validation-report.md").display().to_string(),
            ),
            value(
                "PLAN_CONTEXT_ROOT",
                plan.join("context").display().to_string(),
            ),
            value("PLAN_STEPS_ROOT", plan.join("steps").display().to_string()),
        ],
    );
}

fn manifest_check(path: &Path, expected: &[&str]) {
    if !path.exists() {
        die(format!("manifest is missing: {}", path.display()), 66)
    }
    if fs::symlink_metadata(path)
        .map(|m| m.file_type().is_symlink())
        .unwrap_or(false)
    {
        die(
            format!("manifest must not be a symlink: {}", path.display()),
            65,
        )
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::{MetadataExt, PermissionsExt};
        let m = fs::metadata(path).unwrap();
        if m.permissions().mode() & 0o777 != 0o600 {
            die(format!("manifest mode must be 600: {}", path.display()), 65)
        }
        if m.uid() != current_uid() {
            die(
                format!(
                    "manifest owner must be the current user: {}",
                    path.display()
                ),
                65,
            )
        }
    }
    let text = fs::read_to_string(path).unwrap_or_else(|_| {
        die(
            format!("manifest is not valid shell syntax: {}", path.display()),
            65,
        )
    });
    let mut keys = Vec::new();
    for line in text.lines() {
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            die(
                format!("invalid manifest assignment in {}", path.display()),
                65,
            )
        };
        if !key.bytes().enumerate().all(|(i, b)| {
            if i == 0 {
                b == b'_' || b.is_ascii_uppercase()
            } else {
                b == b'_' || b.is_ascii_uppercase() || b.is_ascii_digit()
            }
        }) {
            die(
                format!("invalid manifest assignment in {}", path.display()),
                65,
            )
        }
        if keys.iter().any(|k| k == key) {
            die(
                format!("duplicate manifest key {key} in {}", path.display()),
                65,
            )
        }
        keys.push(key.to_string());
        if value.chars().any(|c| "$`;|&<>~\n".contains(c)) {
            die(
                format!("unsafe manifest value for {key} in {}", path.display()),
                65,
            )
        }
        if !expected.contains(&key) {
            die(
                format!("unexpected manifest key {key} in {}", path.display()),
                65,
            )
        }
    }
    for key in expected {
        if !keys.iter().any(|k| k == key) {
            die(
                format!("missing manifest key {key} in {}", path.display()),
                65,
            )
        }
    }
}

#[cfg(unix)]
fn current_uid() -> u32 {
    use std::os::unix::fs::MetadataExt;
    fs::metadata(".").unwrap().uid()
}

fn main() {
    let args: Vec<String> = env::args().collect();
    match args.get(1).map(String::as_str) {
        Some("--help") | Some("-h") => usage(0),
        Some("write-global") if args.len() == 4 => {
            write_global(Path::new(&args[2]), Path::new(&args[3]))
        }
        Some("write-plan") if (2..=4).contains(&(args.len() - 1)) => write_plan(
            Path::new(&args[2]),
            args.get(3).map(String::as_str),
            args.get(4).map(String::as_str),
        ),
        Some("path") if (3..=4).contains(&(args.len() - 1)) => match args[2].as_str() {
            "global" => println!(
                "{}",
                global_path(&plans_root(args.get(4).map(String::as_str))).display()
            ),
            "plan" => println!("{}", plan_path(Path::new(&args[3])).display()),
            _ => usage(64),
        },
        Some("check") if (2..=3).contains(&(args.len() - 1)) => {
            let plan = absolute(&args[2]);
            let root = absolute(
                &plans_root(args.get(3).map(String::as_str))
                    .display()
                    .to_string(),
            );
            manifest_check(
                &global_path(&root),
                &[
                    "PLAN_ENV_SCHEMA_VERSION",
                    "PLANS_ROOT",
                    "PLANNING_SKILL_ROOT",
                    "PLANNING_SCRIPTS_ROOT",
                    "PLANNING_TESTS_ROOT",
                ],
            );
            manifest_check(
                &plan_path(&plan),
                &[
                    "PLAN_ENV_SCHEMA_VERSION",
                    "PLAN_SNAPSHOT_REPO",
                    "PLANS_ROOT",
                    "PLAN_ROOT",
                    "PLAN_NAME",
                    "GLOBAL_PLANS_ENV_FILE",
                    "PLAN_ENV_FILE",
                    "PLAN_DESCRIPTION_FILE",
                    "PLAN_PROGRESS_FILE",
                    "PLAN_WORK_UNIT_INVENTORY",
                    "PLAN_VALIDATION_FILE",
                    "PLAN_CONTEXT_ROOT",
                    "PLAN_STEPS_ROOT",
                ],
            );
            println!("plan-env: manifests valid for {}", args[2]);
        }
        Some("print") if (2..=3).contains(&(args.len() - 1)) => {
            let plan = absolute(&args[2]);
            let root = plans_root(args.get(3).map(String::as_str));
            manifest_check(
                &global_path(&root),
                &[
                    "PLAN_ENV_SCHEMA_VERSION",
                    "PLANS_ROOT",
                    "PLANNING_SKILL_ROOT",
                    "PLANNING_SCRIPTS_ROOT",
                    "PLANNING_TESTS_ROOT",
                ],
            );
            manifest_check(
                &plan_path(&plan),
                &[
                    "PLAN_ENV_SCHEMA_VERSION",
                    "PLAN_SNAPSHOT_REPO",
                    "PLANS_ROOT",
                    "PLAN_ROOT",
                    "PLAN_NAME",
                    "GLOBAL_PLANS_ENV_FILE",
                    "PLAN_ENV_FILE",
                    "PLAN_DESCRIPTION_FILE",
                    "PLAN_PROGRESS_FILE",
                    "PLAN_WORK_UNIT_INVENTORY",
                    "PLAN_VALIDATION_FILE",
                    "PLAN_CONTEXT_ROOT",
                    "PLAN_STEPS_ROOT",
                ],
            );
            print!(
                "{}{}",
                fs::read_to_string(global_path(&root)).unwrap(),
                fs::read_to_string(plan_path(&plan)).unwrap()
            );
        }
        _ => usage(64),
    }
}
